variables:
  EXTERNAL_GIT_DIR: "/external-git"

stages:
  - tests
  - deploy

library:
  stage: tests
  image: continuumio/miniconda3:latest
  script:
    - mkdir $EXTERNAL_GIT_DIR
    - CI_DIR=$PWD

    # Attempt to download the private repo `monorepo`. If access is not
    # available set an env variable `RUN_PRIVATE_TESTS=no`
    - cd $EXTERNAL_GIT_DIR; export RUN_PRIVATE_TESTS=yes && git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/CCA-Physics/monorepo.git || export RUN_PRIVATE_TESTS=no; cd $CI_DIR
    - bash ./scripts/gitlab-ci-pipelines/tests/library/01-install-pymedphys.sh
    - bash ./scripts/gitlab-ci-pipelines/tests/library/02-check-nbstripout.sh

    # Only install private packages if `RUN_PRIVATE_TESTS` is set to yes
    - if [ "$RUN_PRIVATE_TESTS" = yes ]; then bash ./scripts/gitlab-ci-pipelines/tests/library/03-install-private.sh; fi
    - bash ./scripts/gitlab-ci-pipelines/tests/library/04-test.sh

application:
  stage: tests
  image: electronuserland/builder:wine-chrome
  script:
    - bash ./scripts/gitlab-ci-pipelines/tests/application/01-build-application.sh
