[build]
  command = "pymedphys dev docs --output build"
  publish = "build"

[[redirects]]
  from = "/en/stable/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/en/latest/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/en/0.8.x/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/en/0.7.x/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/en/0.6.x/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/en/0.5.x/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://app.pymedphys.com/*"
  to = "https://share.streamlit.io/pymedphys/pymedphys/main/app.py/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://pymedphys.netlify.com/*"
  to = "https://docs.pymedphys.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://pymedphys.com/*"
  to = "https://docs.pymedphys.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://docs-pymedphys.netlify.com/*"
  to = "https://docs.pymedphys.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://app-pymedphys.netlify.com/*"
  to = "https://app.pymedphys.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/getting-started/installation.html"
  to = "/howto/get-started.html"
  status = 301
  force = true

[[redirects]]
  from = "/getting-started/licensing.html"
  to = "/background/open-source-benefits.html"
  status = 301
  force = true

[[redirects]]
  from = "/developer/agpl-benefits.html"
  to = "/background/open-source-benefits.html"
  status = 301
  force = true

[[redirects]]
  from = "/explain/agpl-benefits.html"
  to = "/background/open-source-benefits.html"
  status = 301
  force = true

[[redirects]]
  from = "/explain/license.html"
  to = "/background/open-source-benefits.html"
  status = 301
  force = true

[[redirects]]
  from = "/developer/file-structure.html"
  to = "/background/file-structure.html"
  status = 301
  force = true

[[redirects]]
  from = "/projects/elekta-logfiles.html"
  to = "/background/elekta-logfiles.html"
  status = 301
  force = true

[[redirects]]
  from = "/user/gamma.html"
  to = "/howto/gamma/from-dicom.html"
  status = 301
  force = true
