[build]
  command = """
restore_home_cache ".cache" "pip cache" &&
restore_cwd_cache '.venv' 'python virtualenv' &&
pip3 install -q poetry &&
poetry install -vvv --no-dev -E docs -E library -E labs &&
poetry run sphinx-build -W docs docs/_build/html
"""

  publish = "docs/_build/html"

[[redirects]]
  from = "/en/stable/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/en/latest/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/en/0.8.x/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/en/0.7.x/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/en/0.6.x/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/en/0.5.x/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://pymedphys.netlify.com/*"
  to = "https://docs.pymedphys.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://pymedphys.com/*"
  to = "https://docs.pymedphys.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://docs-pymedphys.netlify.com/*"
  to = "https://docs.pymedphys.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://app-pymedphys.netlify.com/*"
  to = "https://app.pymedphys.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/getting-started/installation.html"
  to = "/tutes/install.html"
  status = 301
  force = true

[[redirects]]
  from = "/getting-started/licensing.html"
  to = "/explain/license.html"
  status = 301
  force = true

[[redirects]]
  from = "/developer/agpl-benefits.html"
  to = "/explain/agpl-benefits.html"
  status = 301
  force = true

[[redirects]]
  from = "/explain/agpl-benefits.html"
  to = "/explain/open-source-benefits.html"
  status = 301
  force = true

[[redirects]]
  from = "/explain/license.html"
  to = "/explain/open-source-benefits.html"
  status = 301
  force = true

[[redirects]]
  from = "/developer/file-structure.html"
  to = "/contrib/explain/file-structure.html"
  status = 301
  force = true

[[redirects]]
  from = "/projects/elekta-logfiles.html"
  to = "/explain/elekta-logfiles.html"
  status = 301
  force = true
