# Copyright (C) 2019 Cancer Care Associates

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version (the "AGPL-3.0+").

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License and the additional terms for more
# details.

# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# ADDITIONAL TERMS are also included as allowed by Section 7 of the GNU
# Affero General Public License. These additional terms are Sections 1, 5,
# 6, 7, 8, and 9 from the Apache License, Version 2.0 (the "Apache-2.0")
# where all references to the definition "License" are instead defined to
# mean the AGPL-3.0+.

# You should have received a copy of the Apache-2.0 along with this
# program. If not, see <http://www.apache.org/licenses/LICENSE-2.0>.

version: "3.6"

services:
  physics-server-orthanc-machine-id-editor:
    restart: unless-stopped
    build: orthanc/orthanc-and-miniconda
    ports: ["34242:4242", "38042:8042"]

    volumes:
      - ./orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./orthanc/scripts:/etc/share/orthanc/scripts:ro
      - ../../../../../.:/usr/src/pymedphys:ro
      - pypi-cache:/root/.cache/pip:rw

    entrypoint: /bin/bash -c
    command: ['pushd /usr/src/pymedphys && yarn docker:internal && popd && /docker-entrypoint.sh --verbose /etc/orthanc']

  physics-server-nginx:
    restart: always
    image: nginx:1.15
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

volumes:
  pypi-cache:
