steps:
  - bash: echo $PATH && source activate pymedphys && pip install -e .
    displayName: 'Install development version of PyMedPhys'
  - bash: ./azure-pipelines/scripts/matplotlib-backend.sh
    displayName: 'Set matplotlib backend to Agg'
  - bash: source activate pymedphys && find . -iname \*.ipynb | xargs -d "\n" nbstripout && git add -A && git diff HEAD --name-only --exit-code -- '*ipynb'
    displayName: 'Check that notebooks have no included output'
  - bash: source activate pymedphys && python setup.py test
    displayName: 'Run the full pytest suite'
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFiles: junit/*.xml
      testRunTitle: 'Library'
    condition: succeededOrFailed()
