name: PullRequest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

# =============================================================================

  PreCommit:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Test branch name
        run: |
          echo ${{ steps.extract_branch.outputs.branch }}
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-cache

      - name: Run Pre-Commit
        run: |
          pip install pre-commit
          pre-commit run --all-files
      - name: Fix any issues
        if: failure()
        run: |
          git config --local user.email "pre-commit-bot@pymedphys.com"
          git config --local user.name "PyMedPhys Pre-Commit Bot"
          git commit -m "Fix pre-commit failures" -a
          exit 1
      - name: Push changes
        if: failure()
        uses: ad-m/github-push-action@02b0b75
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}

# =============================================================================

  Tests:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu', 'macos', 'windows']
        task: ['tests', 'docs', 'stackoverflow', 'updates']
        exclude:
          - os: 'windows'
            task: 'stackoverflow'
          - os: 'windows'
            task: 'updates'

          - os: 'macos'
            task: 'stackoverflow'
          - os: 'macos'
            task: 'updates'

        include:
          - os: 'ubuntu'
            python-version: 3.7
          - os: 'windows'
            python-version: 3.7
          - os: 'macos'
            python-version: 3.7

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Get full Python version
      id: full-python-version
      shell: bash
      run: |
        echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")

# Set up pip

    - name: Get pip cache dir
      id: pip-cache
      run: |
        python -m pip install -U pip # to ensure version > 20 to have cache dir
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Pip Cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: pip-${{ matrix.task }}-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}

# Install poetry

    - name: Upgrade pip, upgrade setuptools and install poetry
      run: |
        pip install --upgrade pip setuptools
        pip install poetry

# No import and run CLI with no dependencies

    - name: Build wheel and install core dependencies
      if: matrix.task == 'tests'
      run: |
        poetry build --format wheel
        pip install -r requirements-core.txt

    - name: Install wheel
      if: matrix.task == 'tests' && matrix.os == 'windows'
      run: |
        python -m pip install (Get-Item .\dist\*.whl) --no-dependencies

    - name: Install wheel
      if: matrix.task == 'tests' && matrix.os != 'windows'
      run: |
        python -m pip install ./dist/*.whl --no-dependencies

    - name: Run clean tests
      if: matrix.task == 'tests'
      run: |
        pymedphys --help
        python -c "import pymedphys"

# Set up Poetry

    - name: Configure poetry
      run: |
        poetry config virtualenvs.in-project true

    - name: Poetry Cache
      uses: actions/cache@v2
      id: poetry-cache
      with:
        path: .venv
        key: venv-${{ matrix.task }}-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Ensure cache is healthy
      if: steps.poetry-cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        poetry run pip --version >/dev/null 2>&1 || rm -rf .venv

# System installs

    - name: Install FreeTDS on MacOS
      if: matrix.os == 'macos'
      run: |
        brew install freetds

    - name: Install Pandoc on Ubuntu
      if: matrix.task == 'docs' && matrix.os == 'ubuntu'
      run: |
        sudo apt-get install -y pandoc

    - name: Install Pandoc on MacOS
      if: matrix.task == 'docs' && matrix.os == 'macos'
      run: |
        brew install pandoc

    - name: Install Pandoc on Windows
      if: matrix.task == 'docs' && matrix.os == 'windows'
      run: |
        choco install pandoc

## Plain install

    - name: Install a plain environment
      if: matrix.task == 'stackoverflow'
      run: |
        poetry install --no-dev


## Install with Documentation Environment

    - name: Install a docs environment
      if: matrix.task == 'docs'
      run: |
        poetry install --no-dev -E docs

## Install with Tests Environment

    - name: Install a tests environment
      if: matrix.task == 'tests'
      run: |
        poetry install --no-dev -E tests

## Install Machine Learning Dependencies

    - name: Install a machine learning environment
      if: matrix.task == 'tests' && matrix.os == 'ubuntu'
      run: |
        poetry install --no-dev -E ml

## Update all packages and then install with tests environment and

    - name: Update all packages then install with tests environment
      if: matrix.task == 'updates'
      run: |
        poetry update
        poetry install --no-dev -E tests


# Download all data for consistent cache

    - name: Get PyMedPhys cache directory
      id: pymedphys-cache-location
      run: |
        echo "::set-output name=dir::$(poetry run python -c 'import pymedphys._config as cf; print(str(cf.get_config_dir()))')"

    - name: PyMedPhys Cache
      id: pymedphys-cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pymedphys-cache-location.outputs.dir }}
        key: pymedphys-${{ hashFiles('**/hashes.json') }}

    - name: Download all PyMedPhys data for a consistent cache
      if: steps.pymedphys-cache.outputs.cache-hit != 'true'
      run: |
        poetry run python -c "from pymedphys._data import download; download.download_all()"


# TESTS

## Pytest

    - name: Run basic pytest tests
      if: matrix.task == 'tests' || matrix.task == 'updates'
      run: |
        poetry run pymedphys dev tests -v

## Doctest

    - name: Run doctest tests
      if: matrix.os == 'ubuntu' && matrix.task == 'tests'
      run: |
        poetry run pymedphys dev tests -v --doctest-modules

## Pylint

    - name: Run pylint tests
      if: matrix.os == 'ubuntu' && ( matrix.task == 'tests' || matrix.task == 'updates' )
      run: |
        poetry run pymedphys dev tests --pylint --pylint-jobs=1

## Slow

    - name: Run slow tests
      if: matrix.os == 'ubuntu' && matrix.task == 'tests'
      run: |
        poetry run pymedphys dev tests -v --run-only-slow

## Docs

    - name: Build docs
      if: matrix.task == 'docs'
      run: |
        poetry run pymedphys dev docs

## Stackoverflow

    - name: Run stackoverflow example(s)
      if: matrix.task == 'stackoverflow'
      run: |
        poetry run python ./examples/stackoverflow/gamma.py

## Cypress

    - uses: actions/setup-node@v1
      if: matrix.os == 'ubuntu' && matrix.task == 'tests'

    - name: Initially run Cypress tests only locally, without dashboard integration
      if: matrix.os == 'ubuntu' && matrix.task == 'tests'
      run: |
        poetry run pymedphys dev tests -v -s --run-only-yarn

    - name: Delete GUI demo data and run the PyMedPhys GUI
      if: failure() && matrix.os == 'ubuntu' && matrix.task == 'tests'
      run: |
        rm -rf pymedphys-gui-demo
        poetry run pymedphys gui &

    - name: Run Cypress through the dashboard tool so as to see the failures
      if: failure() && matrix.os == 'ubuntu' && matrix.task == 'tests'
      uses: cypress-io/github-action@v1
      with:
        install: true
        record: true
        start: yarn start
        working-directory: tests/e2e
        wait-on: 'http://localhost:8501'
      env:
        # pass the Dashboard record key as an environment variable
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        host: localhost
        port: 8501
